# Generated by Django 2.1.8 on 2019-05-05 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManageIP',
            fields=[
                ('ip_address', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='封闭地址')),
                ('ip_status', models.BooleanField(default=False, verbose_name='封闭状态')),
                ('ip_datetime', models.DateTimeField(auto_now=True, verbose_name='封闭时间')),
            ],
            options={
                'verbose_name': '管理IP',
                'verbose_name_plural': '管理IP',
            },
        ),
    ]
